language: node_js

node_js:
- "node"

services:
  - docker

env:
  global:
    - IMAGE_NAME=shindepriyankasa/demo
    - REGISTRY_USER=shidnepriyankasa
    - REGISTRY_PASS=Qwest@666
    - secret: "<something long>"

before_script:
  - version="$(awk '$2 == "DEMO_SERVICE_VERSION" { print $3; exit }' Dockerfile)"
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master  
  
 
